// Generated by CoffeeScript 1.6.3
(function() {
  var eField, i, num, radius, x, xi, y, yi, _i,
    _this = this;

  eField = new EField();

  eField.render($('#gauss'));

  eField.drawArrows();

  x = 365;

  y = 300;

  radius = 200;

  num = 20;

  for (i = _i = 1; 1 <= num ? _i <= num : _i >= num; i = 1 <= num ? ++_i : --_i) {
    xi = Math.sin(i * 360 / num * Math.PI / 180) * radius;
    yi = Math.cos(i * 360 / num * Math.PI / 180) * radius;
    eField.addStationaryCharge(x + xi, y + yi);
    eField.addStationaryCharge(x - xi, y + yi);
  }

  eField.toplayer.click(function(e) {
    if (e.shiftKey) {
      return eField.addStationaryCharge(e.offsetX, e.offsetY);
    } else {
      return eField.addPointCharge(e.offsetX, e.offsetY);
    }
  });

}).call(this);
